# Example docker-compose configuration for Review Board on Postgres.
#
# Please note, this file is meant to be used as an example! You will need
# to change some settings first. See the instructions.
#
#
# Instructions
# ============
#
# 1. Copy the following to a new directory:
#
#    * docker-compose.yaml (based on this file)
#    * nginx_templates/
#    * postgres/
#
# 2. Change the hostname below to a fully-qualified domain name you'll be
#    able to use for the server. Search for "localhost" for the default.
#
#    See DOMAIN and NGINX_HOST below.
#
#    To temporarily test a hostname, you can modify /etc/hosts on Linux
#    or macOS and alias it to your IP address.
#
#    NOTE: If you change this later, you will need to edit the sitedir
#          volume's conf/settings_local.py to include the new hostname in
#          ALLOWED_HOSTS, and change the hostname in Review Board's
#          Admin UI -> General Settings page.
#
# 3. Change the database passwords below to something secure.
#
#    See POSTGRES_PASSWORD, POSTGRES_RB_PASSWORD, and DATABASE_PASSWORD.
#
# 4. Change the company name for your server.
#
#    See COMPANY below.
#
# 5. Go through this file and search for "CHANGEME" for other settings you
#    may want to change.
#
# 6. Run: docker-compose up
#
# 7. Access http://<hostname>/
#
#
# Data Storage
# ============
#
# This example configuration will create two directories for storage:
#
# db_data/
#     The Postgres database contents.
#
#     This CANNOT be shared across multiple Postgres database servers.
#
# sitedir/
#     Review Board site directory content (static media files, data, and
#     configuration).
#
#     This CAN be shared across multiple Review Board server instances, and
#     Nginx instances.
#
#
# Production Use
# ==============
#
# As this is only a sample configuration, you'll likely want to make other
# changes for production use, such as:
#
# 1. Setting up a load balancer with SSL enabled.
#
# 2. Separating out the database and memcached server for other Review Board
#    instances to use.
#
# 3. Making sure only port 80 is accessible on the network.
#
# These are all beyond the scope of this example configuration.
#
# You should also go through this file, read the comments, and change any
# configuration needed for your install.

version: '3.7'


services:
  # The backend Postgres database server.
  #
  # This is accessed directly by Review Board.
  #
  # In production, this should be shared across all Review Board instances.
  db:
    image: postgres:13-alpine
    environment:
      # The Postgres admin username.
      - POSTGRES_USER=admin

      # The Postgres admin password.
      #
      # CHANGEME: Use a strong password!
      - POSTGRES_PASSWORD=${DATABASE_ROOT_PASSWORD}

      # The name of the Postgres database storing Review Board content.
      - POSTGRES_DB=reviewboard

      # The Postgres username for Review Board.
      - POSTGRES_RB_USER=reviewboard

      # The Postgres password for Review Board.
      #
      # CHANGEME: Use a strong password!
      - POSTGRES_RB_PASSWORD=${DATABASE_RB_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data/
      - ./postgres/init-reviewboard-db.sh:/docker-entrypoint-initdb.d/init-reviewboard-db.sh

    restart: 'on-failure'


  # The backend memory caching server.
  #
  # This is accessed directly by Review Board.
  #
  # In production, this should be shared across all Review Board instances,
  # and should be configured with at least 2GB of RAM.
  memcached:
    image: memcached:alpine
    restart: 'on-failure'

    entrypoint:
      - memcached

      # The amount of RAM available for memcached.
      #
      # CHANGEME: Set this to a suitable amount for your server. We recommend
      #           at least 2GB in production (2048).
      - -m 256


  # The backend Review Board server.
  #
  # This should not be accessed directly. Instead, please access the frontend
  # nginx server.
  reviewboard:
    image: ${REVIEWBOARD_IMAGE:-beanbag/reviewboard:6.0}
    depends_on:
      - db
      - memcached

    environment:
      - DATABASE_TYPE=postgresql

      # The name of your company.
      #
      # CHANGEME: You should use your actual name here. It's used for
      #           internal state and your in-app support page.
      - COMPANY=${COMPANY}

      - SITE_ROOT=${SITE_ROOT:-/}

      # CHANGEME: Set this to the database username above.
      - DATABASE_USERNAME=reviewboard

      # CHANGEME: Set this to the database password above.
      - DATABASE_PASSWORD=${DATABASE_RB_PASSWORD}

      # CHANGEME: Set this to your accessible domain name.
      - DOMAIN=${DOMAIN}

    volumes:
      - sitedir:/site


  # The frontend nginx web server.
  #
  # This serves up static media (CSS, JavaScript, and images), and forwards
  # all other requests to the Review Board backend server.
  #
  # This is the server you will access for Review Board.
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - reviewboard

    environment:
      # CHANGEME: Set this to your accessible domain name above.
      - NGINX_HOST=${DOMAIN}

      # The public port used to access this instance.
      #
      # If changed, you will need to change 'ports' below to match.
      - NGINX_PORT=80

    ports:
      - 80:80

    volumes:
      - sitedir:/var/www/reviewboard
      - ./nginx_templates:/etc/nginx/templates


volumes:
  db_data:
  sitedir:
